version: 2

# Modern RTD configuration. Python 3.7 is EOL and no longer provided by current build images.
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc